### ISSUE TITLE
A Reinforced Topic-Aware Convolutional Sequence-to-Sequence Model for Abstractive Text Summarization

### ISSUE THREAD

**Issue by gsh199449** [gsh199449/read-paper#31]
# title
A Reinforced Topic-Aware Convolutional Sequence-to-Sequence Model for Abstractive Text Summarization

# notes

# bibtex

# link
https://arxiv.org/abs/1805.03616

# publication
IJCAI 2018 

# open source
No

# affiliated
Tencent

**Comment by gsh199449** [comment]
duplicate

**Comment by shirinkhan17** [comment]
would you please provide the source code of this paper.

**Comment by gsh199449** [comment]
@shirinkhan17 I'm not the author of this paper, this issue is just a note.
